### ISSUE TITLE
Making UI better

### ISSUE THREAD

**Issue by samarth-1729** [samarth-1729/real-time-chat-app#1]
Make the front-end of the look bit more good

**Comment by GustavoTxFreitas-zz** [comment]
Hi, @samarth-1729!
Do you have any idea about what do you want?
Maybe I can help you, contributing to this repository.

Tell me about this project, you can contact me by this issue or by my [email](dev.gustavotxfreitas@gmail.com)!

See you soon, [Gustavo Teixeira](https://github.com/GustavoTxFreitas).

**Comment by samarth-1729** [comment]
Hello,
This is a simple chat room that I have created using socket.io, You can clone this and see how its front-end is looking I want to make it better like a real chat room,
Your contribution will surely help me.

Thank you, [Samarth Potdar](https://github.com/samarth-1729)

**Comment by GustavoTxFreitas-zz** [comment]
Good Afternoon, @samarth-1729!
I was learning about your code and I have a lot of ideas to help, but now I'm without my computer.

While I'm without him, I wont be able to contribute. As soon as I can, I'll fork the repository and work with you.

See you later!
@GustavoTxFreitas.

**Comment by samarth-1729** [comment]
Hello,
Your ideas would be highly appreciated. 
If you don't have a computer with you, no problem you can start working with it anytime you want.

Thank you, [Samarth Potdar](https://github.com/samarth-1729)

**Comment by GustavoTxFreitas-zz** [comment]
Hello @samarth-1729,
With pleasure that I come to announce: I'm back!

I finally recovered my computer, so I designed a sketch of some components this morning;
Everything was done with Bootstrap4 components in mind, so I'll be able to easily modify the current project.

Give me your opinion!
[Gustavo Teixeira](https://github.com/GustavoTxFreitas)
<hr>
<p align="center">
<img src="https://user-images.githubusercontent.com/62919596/96721854-12ae7a00-1383-11eb-8c47-9ae2ea25d179.png" height="350"/>
</p>

**Comment by samarth-1729** [comment]
Hi,
This design looks very nice!
Go ahead with this, just make the send button horizontal

**Comment by GustavoTxFreitas-zz** [comment]
Good Morning, @samarth-1729!
You can check the changes in the pull request https://github.com/samarth-1729/real-time-chat-app/pull/3

I would like to stress that I have not changed the logic and functionality of the application, the changes were aimed exclusively at a more pleasant interface.

Thank you for allowing me to participate in your wonderful project!
